### ISSUE TITLE
99 NC project epic

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/open-community-survey#121]
### Overview
We need to manage the 99 NC C&C analysis project so that we can be as efficient as possible

### Action Items
- [ ] Define the purpose of each issue (copy the overview) to a list below
- [ ] Identify the order of issues
- [ ] Identify issues that are on the Data Science repo
- [ ] That dependencies are accurate
- [ ] What the current overall status is

#### List of issues
- #69 
- #52
- #35
- #28 
- #25 
- #12

**Comment by ExperimentsInHonesty** [comment]
Current status is
This is the issue where we track DS's current deliverable: https://github.com/hackforla/open-community-survey/issues/25
We have assigned Snow to this issue because she is the only remaining team member who knows what happened #75
