### ISSUE TITLE
Create project roadmap

### ISSUE THREAD

**Issue by ebele-oputa** [hackforla/open-community-survey#43]
### Overview
We need to create a roadmap that includes the milestone list to help with product prioritisation, project monitoring and for the team to know what each task builds up to.

### Action Items
- [x] Create milestone list using Guides template and project one sheet as examples
- [x] Meet with Bonnie to create list
- [x] Add Milestones to Repo
- [x] Add Milestones to each issue
- [x] Release dependency on issue #13

### Resources/Instructions
[Guides Project Roadmap](https://docs.google.com/spreadsheets/d/1xYUlIKsfE2-CeExIQ8i3oLD8pC7hjMTPM2YLSMFA8_s/edit#gid=0)
[OCS Project Roadmap](https://docs.google.com/spreadsheets/d/163RPNWPhkeah2OvGCqjByMukYduXk66XY7ZpcpLCzXU/edit#gid=0)

**Comment by ebele-oputa** [comment]
@ebele-oputa  add document naming to the communication design

**Comment by ebele-oputa** [comment]
@jonarcisse Done with the last 10. Over to you!

**Comment by ebele-oputa** [comment]
Discuss #45 during the next meeting

**Comment by ebele-oputa** [comment]
@jonarcisse when are you available to meet next week to complete the task items? I am unavailable Tuesday - Thursday as I will be on vacation.

**Comment by ebele-oputa** [comment]
- [ ] Add issues by role
   - [ ] Data Science
   - [ ] Product 
   - [ ] UI/UX Research
   - [ ] Design

**Comment by ExperimentsInHonesty** [comment]
[Issues missing a feature and or feature missing label](https://github.com/hackforla/open-community-survey/issues?q=is%3Aopen+is%3Aissue+-label%3A%22feature%3A+Board%2FGitHub+Maintenance%22+-label%3A%22feature%3A+Comparative+Analysis%22+-label%3A%22feature%3A+Epic%22+-label%3A%22feature%3A+Expert+Interviews%22+-label%3A%22feature%3A+Figma%2FMiro%2FFigJam+setup%22+-label%3A%22feature%3A+Framework+Project+Publication%22+-label%3A%22feature%3A+Guides+Creation%22+-label%3A%22feature%3A+HfLA+Website%22+-label%3A%22feature%3A+Impact+Interview%22+-label%3A%22feature%3A+Meeting%2FAgenda%22+-label%3A%22feature%3A+Missing%22+-label%3A%22feature%3A+Onboarding%22+-label%3A%22feature%3A+Personas%22+-label%3A%22feature%3A+Recruitment%22+-label%3A%22feature%3A+Roadmap%22+-label%3A%22feature%3A+Social+Media%22+-label%3A%22feature%3A+Survey%22+-label%3A%22feature%3A+Usability+Testing%22+-label%3A%22feature%3A+Website+Content%22+-label%3A%22feature%3A+1Password%22+-label%3A%22p-feature%3A+About+Us%22+-label%3A%22p-feature%3A+Credits%22+-label%3A%22p-feature%3A+Donate%22+-label%3A%22p-feature%3A+EmpowerLA+Website+Page%22+-label%3A%22p-feature%3A+Home+Page%22+-label%3A%22p-feature%3A+Navigation%22+-label%3A%22p-feature%3A+NC+Websites+Analysis+Page%22+-label%3A%22p-feature%3A+NC+Websites+Page%22+-label%3A%22p-feature%3A+Privacy+Policy%22+-label%3A%22p-feature%3A+Projects%22+-label%3A%22feature%3A+Communication%2FBranding%22+-label%3A%22feature%3A+Figma%2FMiro%2FFigJam+Setup%22+-label%3A%22feature%3A+One+Sheet%22+-label%3A%22p-feature%3A+Get+Involved%22+-label%3A%22feature%3A+Analytics%22+-label%3A%22p-feature%3A+Website+Content%22)

**Comment by ExperimentsInHonesty** [comment]
yeah!!!!
