### ISSUE TITLE
Create Milestone check Issues

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/open-community-survey#77]
### Overview
We need to make an issue to check each milestone so that we can determine if we have made all the issues for that milestone

### Action Items
- [ ] Make an issue for each milestone using this template (skip 1-5 milestones for now)

### Resources/Instructions
Use this template for the new issues you will create

```
Milestone/Issue check: [name of milestone]
```
```
### Overview
We need to check the [name of milestone ] milestone to see if it has all the issues required to deliver it

###Action Items

- [ ] Grab the details from the milestone and put them into this issue
- [ ] Uncheck the boxes for the labels
- [ ] Add issue links to each label that we have already made the issue, and check as you go, if you think that it will only require that one (e.g, it might have the label usability testing, and we are doing three usability testing inside of the milestone, so you would not check it off yet.
- [ ] Add link to the this milestone issue to the Milestone itself

### Resources
[OCS Milestone page](https://github.com/hackforla/open-community-survey/milestones?direction=asc&sort=title&state=open)
```

**Comment by jonarcisse** [comment]
I created the new issues as requested- all in the [new approval column](https://github.com/hackforla/open-community-survey/projects/1?card_filter_query=label%3A%22feature%3A+roadmap%22)

**Comment by kalyaniraman** [comment]
Milestone/Issue check: [Milestone/Issue Check: w1 requirements #78]

### Overview
We need to check the [w1 requirements  ] milestone to see if it has all the issues required to deliver it

###Action Items

- [X] Grab the details from the milestone and put them into this issue
- [ ] Uncheck the boxes for the labels
- [ ] Add issue links to each label that we have already made the issue, and check as you go, if you think that it will only require that one (e.g, it might have the label usability testing, and we are doing three usability testing inside of the milestone, so you would not check it off yet.
- [ ] Add link to the this milestone issue to the Milestone itself

Action Items
Objective: Have clear first understanding of what goes into the site
What is needed in order to achieve:

Comparative analysis #4
Expert/sme interviews
Feature Labels:

 feature: Comparative Analysis #4
 feature: Impact interview #20
 feature: Usability Testing #41
 feature: Expert Interviews
 feature: Personas #17 #76
 feature: Survey #69
 feature: Analytics #52

### Resources
[OCS Milestone page](https://github.com/hackforla/open-community-survey/milestones?direction=asc&sort=title&state=open)

**Comment by ExperimentsInHonesty** [comment]
Milestone/Issue check: 01. Compliance

### Overview
We need to check the Compliance milestone to see if it has all the issues required to deliver it

###Action Items

- [ ] Grab the details from the milestone and put them into this issue
- [ ] Uncheck the boxes for the labels
- [ ] Add issue links to each label that we have already made the issue, and check as you go, if you think that it will only require that one (e.g, it might have the label usability testing, and we are doing three usability testing inside of the milestone, so you would not check it off yet.
- [ ] Add link to the this milestone issue to the Milestone itself

### Resources
[OCS Milestone page](https://github.com/hackforla/open-community-survey/milestones?direction=asc&sort=title&state=open)

#### Milestone Details
Objective: Make sure that we are not violating any licenses or regulations

What is needed in order to achieve:
- Licensing compliance (credit page for images, etc.)
- Privacy Policy

Feature Labels:
- [ ] p-feature: Credits
- [ ] p-feature: Privacy Policy

**Comment by ExperimentsInHonesty** [comment]
```
- [ ] Grab the details from the milestone and put them into this issue
- [ ] Uncheck the boxes for the labels
- [ ] Add issue links to each label that we have already made the issue, and check as you go, if you think that it will only require that one (e.g, it might have the label usability testing, and we are doing three usability testing inside of the milestone, so you would not check it off yet.
- [ ] Add link to the this milestone issue to the Milestone itself
```
