### ISSUE TITLE
Milestone/Issue Check: w1 requirements

### ISSUE THREAD

**Issue by jonarcisse** [hackforla/open-community-survey#78]
### Overview
We need to check the w1 requirements milestone to see if it has all the issues required to deliver it

### Action Items
- [ ] Grab the details from the milestone and put them into this issue
- [ ] Uncheck the boxes for the labels
- [ ] Add issue links to each label that we have already made the issue, and check as you go, if you think that it will only require that one (e.g, it might have the label usability testing, and we are doing three usability testing inside of the milestone, so you would not check it off yet.
- [ ] Add link to this milestone issue to the Milestone itself

### Resources

[OCS Milestone page](https://github.com/hackforla/open-community-survey/milestones?direction=asc&sort=title&state=open)

#### Objective: Have clear first understanding of what goes into the site

What is needed in order to achieve:
- Comparative analysis https://github.com/hackforla/open-community-survey/issues/4
- Expert/sme interviews

Feature Labels:
- [ ] feature: Comparative Analysis https://github.com/hackforla/open-community-survey/issues/4
- [ ] feature: Impact interview https://github.com/hackforla/open-community-survey/issues/20
- [ ] feature: Usability Testing https://github.com/hackforla/open-community-survey/issues/41
- [ ] feature: Expert Interviews
- [ ] feature: Personas https://github.com/hackforla/open-community-survey/issues/17 https://github.com/hackforla/open-community-survey/issues/76
- [ ] feature: Survey https://github.com/hackforla/open-community-survey/issues/69
- [ ] feature: Analytics https://github.com/hackforla/open-community-survey/issues/52

**Comment by kalyaniraman** [comment]
SME Interviews
- Part of User Impact Research : 
   - Internal people - other volunteers for Hack for LA
   - Neighborhood Council , People who worked for Depart of the Neighborhood empowerment
- Are there other SME's we should be interviewing?

**Comment by kalyaniraman** [comment]
In-order for the NC Website project to appear on the OCS Website while it is in-progress we have to define minimum content.

**Comment by kalyaniraman** [comment]
We identified the Audience Persona
Kalyani to review the User Journey document against the Figma Design
