### ISSUE TITLE
Milestone/Issue check: w1 wireframes

### ISSUE THREAD

**Issue by jonarcisse** [hackforla/open-community-survey#79]
### Overview
We need to check the w1 wireframes milestone to see if it has all the issues required to deliver it

###Action Items

- [ ] Grab the details from the milestone and put them into this issue
- [ ] Uncheck the boxes for the labels
- [ ] Add issue links to each label that we have already made the issue, and check as you go, if you think that it will only require that one (e.g, it might have the label usability testing, and we are doing three usability testing inside of the milestone, so you would not check it off yet.
- [ ] Add link to the this milestone issue to the Milestone itself

### Resources
[OCS Milestone page](https://github.com/hackforla/open-community-survey/milestones?direction=asc&sort=title&state=open)

### Objective: Creative visual presentation of recommendations

What is needed in order to achieve:
- Design 
- Reviews
- Usability surveys (usabilityhub type/dogfooding, not interviews)

Feature Labels:
- [ ] feature: Usability Testing
- [ ] feature: Survey
- [ ] p-feature: About Us
- [ ] p-feature: Credits
- [ ] p-feature: EmpowerLA Website Page
- [ ] p-feature: NC Websites Page
- [ ] p-feature: Home Page
- [ ] p-feature: Navigation
- [ ] p-feature: Privacy Policy
- [ ] p-feature: Projects
- [ ] p-feature: Get Involved Page
- [ ] p-feature: Website content
