### ISSUE TITLE
Milestone/Issue check: w1 development

### ISSUE THREAD

**Issue by jonarcisse** [hackforla/open-community-survey#83]
### Overview
We need to check the w1 development milestone to see if it has all the issues required to deliver it

###Action Items
### Objective: Develop website

What is needed in order to achieve:
- Homepage
- About Us (Define area of operation (City, County, MSA, CSA, etc))
- Project homepage
- EmpowerLA Website Page
- NC Websites Page
- Navigation
- Privacy Policy
- Credits page

Feature Labels:
- [X] p-feature: About Us #53 #72 
- [X] p-feature: Credits #56 
- [X] p-feature: EmpowerLA Website Page 
- [X] p-feature: NC Websites Page #1 
- [X] p-feature: Home Page #73 
- [X] p-feature: Navigation 
- [X] p-feature: Privacy Policy #57 
- [X] p-feature: Projects #14 
- [X] p-feature: Get Involved Page #55 

### Resources
[OCS Milestone page](https://github.com/hackforla/open-community-survey/milestones?direction=asc&sort=title&state=open)
